# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json

translation:
  tra_dir: wildmage/tra

golem:
  mod_dir: wildmage
  platforms:
    - tob
    - bgee
    - bg2ee
    - bgt
    - sod
    - eet
  happy: true

mls:
  translation:
    directory: wildmage/tra/english
