IF
	Global("wm_start","GLOBAL",0)
	Global("wm_bgt","GLOBAL",0)
	GlobalGT("Chapter","GLOBAL",0)
	!Dead("WM_RHIA1")
THEN
	RESPONSE #100
          ActionOverride(Player1,Createcreature("wm_rhia3",[200.3200],0)) 
          SetGlobal("wm_bgt","GLOBAL",1)
          SetGlobal("wm_start","GLOBAL",1)
END

IF
	Global("wm_bgt","GLOBAL",1)
	OR(2)
		Dead("WM_RHIA1")
		Dead("WM_RHIA2")
THEN
	RESPONSE #100
		SetGlobal("wm_bgt","GLOBAL",2)
END